### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sander816** [lokonli/z2mvis#1]
i installed thius, but i am getting
500 Internal Server Error

**Comment by Domoke12** [comment]
Don't forget to put the /
http://ip:port/z2mvis**/**

**Comment by Domoke12** [comment]
I have following error.  Port 9001 (Websockets) is listen, but i cannot get it to work. tried with 127.0.0.1 and the current ip.

MQTT server: undefined State: Error Renderer: dot
MQTT Connection error
Check the MQTT server IP address and the MQTT configuration.

**Comment by sander816** [comment]
Same here now

Op za 14 dec. 2019 17:40 schreef Domoke12 <notifications@github.com>:

**Comment by lokonli** [comment]
Same as issue#2. I'll close this one.
