### ISSUE TITLE
MQTT server: undefined State: Error

### ISSUE THREAD

**Issue by Domoke12** [lokonli/z2mvis#2]
I have following error. Port 9001 (Websockets) is listen, but i cannot get it to work. tried with 127.0.0.1 and the current ip.

MQTT server: undefined State: Error Renderer: dot
MQTT Connection error
Check the MQTT server IP address and the MQTT configuration.

**Comment by lokonli** [comment]
You have to use mqttserver without capital in your config,js
(Sorry, there was a mistake in config_default.js)

Example:

  var z2mvisConfig = {
      mqttserver : '192.168.178.18:9001'
  }

**Comment by lokonli** [comment]
Probably solved.
