### ISSUE TITLE
i see nothing

### ISSUE THREAD

**Issue by advanliempt** [lokonli/z2mvis#3]
i get only:

MQTT server: 192.168.1.8:9001 State: updating Renderer: con
Refresh mode: ManualAuto

thats all!
Do i something wrong?

**Comment by advanliempt** [comment]
Solved!

**Comment by JanvdW304** [comment]
@advanliempt, I am wondering what solved your issue, because I have exactly the same problem.

**Comment by advanliempt** [comment]
Sorry, i don't now. It's a long time a go.

**Comment by JanvdW304** [comment]
That's a pity, because I have exactly the same status message. After some time the message changes in 'MQTT server: <IP number>:9001 State: refresh delay Renderer: con'. And then a popup tells me repeatedly that the page is unresponsive. Does anyone know how to solve it?

**Comment by lokonli** [comment]
I did not test for quite a while already. I'll do some tests this weekend.

**Comment by JanvdW304** [comment]
Great that you will have a look at it; thanks in advance. Do you have an update on the outcome of these tests?

**Comment by lokonli** [comment]
I did a fresh install, tested it, and it's working without issues on my system.

Questions:
How do you serve the webpage?
Is this webserver running on the same system as your mosquitto server?
Do you get an z2mvis page? What is displayed on the first line?

To further debug:
In your browser press F12 to open DevTools, refresh the z2mvis page,
Do you see any error on the console tab? (except for favicon.ico)
There should be a message 'connected' to indicate there is a connection with the mosquitto server.

**Comment by lokonli** [comment]
No update. Issue closed
